# Generated by Django 5.2.4 on 2025-07-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('appaterno', models.CharField(max_length=60)),
                ('apmaterno', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=1)),
                ('fec_nac', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_persona', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_compra', models.CharField(max_length=100, null=True, unique=True)),
                ('codigo_autorizacion', models.CharField(max_length=100, null=True)),
                ('tipo_tarjeta', models.CharField(max_length=50, null=True)),
                ('ultimos_digitos_tarjeta', models.CharField(max_length=4, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
